
spring:
  #mysql数据库配置信息
  datasource:
    url: jdbc:mysql://192.168.83.123:3306/my_test?serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true&useServerPrepStmts=false&allowMultiQueries=true
    username: root
    password: 23321212
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50        # 增加连接池大小
      minimum-idle: 10             # 最小空闲连接
      connection-timeout: 60000    # 连接超时60秒
      idle-timeout: 300000         # 空闲超时5分钟
      max-lifetime: 1800000        # 连接最大生命周期30分钟
      leak-detection-threshold: 60000  # 连接泄漏检测
  # Redis 配置
  redis:
    database: 0
    host: 192.168.83.123
    port: 6379
    timeout: 5000

